<?php
use_helper('I18N');
$culture = $sf_user->getCulture();
?>
<h1 style="border-bottom: 2px solid #E1E1E1; margin-top: 20px; padding-bottom: 8px;"><?php echo __("Key Factors Affecting Exchange Rate") ?></h1>
<p><?php echo __("All forex trading involves the exchange of one currency with another. At any one time, the actual exchange rate is determined by the supply and demand of the corresponding currencies. Keep in mind that the demand of a certain currency is directly linked to the supply of another. Likewise, when you supply a certain currency, it would mean that you have the demand for another currency. The following factors affect the supply and demand of currencies and would therefore influence their exchange rates.") ?></p>
<p><strong><?php echo __("1. Monetary Policy") ?></strong></p>
<p><?php echo __("When a central bank believes that intervention in the forex market is effective and the results would be consistent with the government’s monetary policy, it will participate in forex trading and influence the exchange rates. A central bank generally participates by buying or selling the domestic currency so as to stabilize it at a level that it deems realistic and ideal. Judgment on the possible impact of government’s monetary policy and prediction on future policy by other market players will affect the exchange rates as well.") ?></p>
<p><strong><?php echo __("2. Political Situation") ?></strong></p>
<p><?php echo __("Growing global tension will result in instability in the forex market. Irregular inflow or outflow of currencies may result in significant fluctuations in exchange rates.") ?></p>
<p><?php echo __("The stability of a foreign currency is closely related to the political situation of that place. In general, the more stable the country is, the more stable its currency will be.") ?></p>
<p><?php echo __("We will illustrate how political factors influence exchange rates with some actual examples. At the end of 1987, the US Dollar was suffering from continuous depreciation. In order to stabilize the US Dollar, the G7 Finance Ministers and central bank governors released a joint statement on 23 December 1987 announcing plans for a large-scale intervention in the forex market. On 4 January 1988, the group started to dump Japanese Yen and Deutsche Mark in huge volumes while buying US Dollars. This resulted in a rebound of the US Dollar and maintained its exchange rate at a stable level.") ?></p>
<p><?php echo __("For our second example, if you have been observing the Euro, you would have noticed that for three consecutive months during the Kosovo War, the Euro fell by about 10% against the US Dollar. One of the reasons was the downward pressure on the Euro caused by the Kosovo War.") ?></p>
<p><strong><?php echo __("3. Balance of Payments") ?></strong></p>
<p><?php echo __("Balance of payments of a country will cause the exchange rate of its domestic currency to fluctuate. The balance of payments is a summary of all economic and financial transactions between the country and the rest of the world. It reflects the country’s international economic standing and influences its macroeconomic and microeconomic operations.") ?></p>
<p><?php echo __("The balance of payments can affect the supply and demand for foreign currencies as well as their exchange rates.") ?></p>
<p><?php echo __("An economic transaction, such as export, or capital transaction, such as inflow of foreign investment, will result in foreign revenue. Since foreign currencies are normally not allowed to circulate in the domestic market, there is a need to exchange these currencies into the domestic currency before circulation. This in turn creates a supply of foreign currencies in the forex market. On the other hand, an economic transaction, such as import, or capital transaction, such as outflow of investment to a foreign country, will result in foreign payments. In order to meet a country’s economic needs, it is necessary to convert the domestic currency into foreign currencies. This creates a demand for foreign currencies in the forex market. When all these transactions are consolidated into a table of international balance of payments, this would become the country’s foreign exchange balance of payments. If the foreign revenue is larger than payment, there will be a larger supply of foreign currencies. If the foreign payment is larger than revenue, then the demand for foreign currencies will be higher. When the supply of a foreign currency increases but its demand remains constant, it will directly drive the price of that foreign currency down and increase the value of the domestic currency. On the other hand, when the demand for a foreign currency increases but its supply remains constant, it will drive the price of the foreign currency up and decrease the value of the domestic currency.") ?></p>
<p><strong><?php echo __("4. Interest Rates") ?></strong></p>
<p><?php echo __("When a country’s key interest rate rises higher or falls lower than that of another country, the currency of the nation with lower interest rate will be sold and the other currency will be bought so as to achieve higher returns. Given this increase in demand for the currency with higher interest rate, the value of that currency will rise against other currencies.Let us use an example to illustrate how interest rates affect exchange rates. Assume there are two countries, A and B. Both countries do not exercise foreign exchange control and capital funds can flow freely between them. As part of its monetary policy, Country A raises its interest rate by 1% while the interest rate of Country B remains unchanged. There is a huge volume of liquid capital in the market that flows freely between these two countries, seeking out the best possible interest rate. With all other conditions remaining unchanged, as Country A’s key interest rate rises, a large portion of the liquid capital will flow into Country A. When the liquid capital flows out from Country B to Country A, a large amount of Country B’s currency will be sold in exchange for Country A’s currency. In this way, the demand for Country A’s currency will increase, strengthening it against Country B’s currency.") ?></p>
<p><?php echo __("In fact, in today’s globalized market, this scenario applies to the whole world. Over the years, the market trend has been shifting towards free capital mobility and elimination of foreign exchange restrictions.") ?></p>
<p><?php echo __("This enables liquid capital (also known as “hot money”) to flow freely in the international market. A point to note though is that such capital will only be moved to a region or country with higher interest rate if their investors believe that the change in exchange rate will not nullify the returns gained with higher interest rate.") ?></p>
<p><strong><?php echo __("5. Market Judgment") ?></strong></p>
<p><?php echo __("The forex market does not always follow a logical pattern of change. Exchange rates are also influenced by intangible factors such as emotions, judgments as well as analysis and comprehension of political and economic events. Market operators must be able to interpret reports and data such as balance of payments, inflation indicators and economic growth rates accurately.") ?></p>
<p><?php echo __("In reality, before these reports and data become available to the public, the market would have already made its own predictions and judgments, and these will be reflected in the prices. In the event that the actual reports and data deviate too much from the predictions and judgments of the market, huge fluctuations in exchange rates will occur.Accurate interpretation of reports and data alone is not adequate; a good forex trader must also be able to determine market reactions before the information becomes publicly available.") ?></p>
<p><strong><?php echo __("6. Speculation") ?></strong></p>
<p><?php echo __("Speculation by major market operators is another crucial factor that influences exchange rates. In the forex market, the proportion of transactions that are directly related to international trade activities is relatively low. Most of the transactions are actually speculative trading which cause currency movement and influence exchange rates. When the market predicts that a certain currency will rise in value, it may spark a buying frenzy that pushes the currency up and fulfil the prediction. Conversely, if the market expects a drop in value of a certain currency, people will start selling it away and the currency will depreciate.") ?></p>
<p><?php echo __("For example, after World War II, the United States enjoyed a period of political stability, well-managed economy, low inflation rate and an average annual economic growth of about 5% in the early 1960s. At that time, all the other countries in the world were willing to use US Dollar as the mode of payment to safeguard their wealth. This causes a continuous rise in value of the US Dollar. However, from the end of 1960s to early 1970s, the Vietnam War, Watergate scandal, serious inflation, increased tax burden, trade deficit and declining economic growth caused the US Dollar to plunge in value.") ?></p>
