default:
  http_metas:
    content-type: text/html

  metas:
    title:        CMIS
    robots:       index, follow
    description:  CMIS
    keywords:     CMIS
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
